#define OP_ID                           1
#define OP_INT_CONST                    2
#define OP_FLOAT_CONST                  3
#define OP_BOOL_CONST                   4
#define OP_STRING_CONST                 5
#define OP_LEFT_BRACE                   6
#define OP_RIGHT_BRACE                  7
#define OP_COMA                         8
#define OP_LEFT_PAREN                   9
#define OP_RIGHT_PAREN                 10
#define OP_LEFT_BRACKET                11
#define OP_RIGHT_BRACKET               12
#define OP_DOT                         13
#define OP_INC_OP                      14
#define OP_DEC_OP                      15
#define OP_VOID                        16
#define OP_BOOL                        17
#define OP_INT                         18
#define OP_UINT                        19
#define OP_HALF                        20
#define OP_FLOAT                       21
#define OP_DOUBLE                      22
#define OP_STRING                      23
#define OP_VECTOR                      24
#define OP_LESS                        25
#define OP_MORE                        26
#define OP_MATRIX                      27
#define OP_PLUS                        28
#define OP_DASH                        29
#define OP_BANG                        30
#define OP_TILDE                       31
#define OP_TYPE_NAME                   32
#define OP_STAR                        33
#define OP_SLASH                       34
#define OP_PERCENT                     35
#define OP_LEFT_OP                     36
#define OP_RIGHT_OP                    37
#define OP_LE_OP                       38
#define OP_GE_OP                       39
#define OP_EQ_OP                       40
#define OP_NE_OP                       41
#define OP_AMPERSAND                   42
#define OP_CARET                       43
#define OP_VERTICAL_BAR                44
#define OP_AND_OP                      45
#define OP_OR_OP                       46
#define OP_QUESTION                    47
#define OP_COLON                       48
#define OP_EQUAL                       49
#define OP_MUL_ASSIGN                  50
#define OP_DIV_ASSIGN                  51
#define OP_MOD_ASSIGN                  52
#define OP_ADD_ASSIGN                  53
#define OP_SUB_ASSIGN                  54
#define OP_LEFT_ASSIGN                 55
#define OP_RIGHT_ASSIGN                56
#define OP_AND_ASSIGN                  57
#define OP_XOR_ASSIGN                  58
#define OP_OR_ASSIGN                   59
#define OP_SEMICOLON                   60
#define OP_LINEAR                      61
#define OP_CENTROID                    62
#define OP_NOINTERPOLATION             63
#define OP_NOPERSPECTIVE               64
#define OP_POINT                       65
#define OP_LINE                        66
#define OP_TRIANGLE                    67
#define OP_LINEADJ                     68
#define OP_TRIANGLEADJ                 69
#define OP_IN                          70
#define OP_OUT                         71
#define OP_INOUT                       72
#define OP_PACKOFFSET                  73
#define OP_REGISTER                    74
#define OP_EXTERN                      75
#define OP_PRECISE                     76
#define OP_SHARED                      77
#define OP_GROUPSHARED                 78
#define OP_STATIC                      79
#define OP_UNIFORM                     80
#define OP_VOLATILE                    81
#define OP_CONST                       82
#define OP_ROW_MAJOR                   83
#define OP_COLUMN_MAJOR                84
#define OP_SAMPLER                     85
#define OP_SAMPLERCOMPARISON           86
#define OP_SAMPLER1D                   87
#define OP_SAMPLER2D                   88
#define OP_SAMPLER3D                   89
#define OP_SAMPLERCUBE                 90
#define OP_TEXTURE                     91
#define OP_TEXTURE1D                   92
#define OP_TEXTURE1DARRAY              93
#define OP_TEXTURE2D                   94
#define OP_TEXTURE2DARRAY              95
#define OP_TEXTURE3D                   96
#define OP_TEXTURE3DARRAY              97
#define OP_TEXTURECUBE                 98
#define OP_TEXTURECUBEARRAY            99
#define OP_TEXTURE2DMS                 100
#define OP_TEXTURE2DMSARRAY            101
#define OP_BUFFER                      102
#define OP_APPENDSTRUCTUREDBUFFER      103
#define OP_BYTEADDRESSBUFFER           104
#define OP_CONSUMESTRUCTUREDBUFFER     105
#define OP_INPUTPATCH                  106
#define OP_OUTPUTPATCH                 107
#define OP_RWBUFFER                    108
#define OP_RWBYTEADDRESSBUFFER         109
#define OP_RWSTRUCTUREDBUFFER          110
#define OP_RWTEXTURE1D                 111
#define OP_RWTEXTURE2D                 112
#define OP_RWTEXTURE3D                 113
#define OP_RWTEXTURE1DARRAY            114
#define OP_RWTEXTURE2DARRAY            115
#define OP_RWTEXTURE3DARRAY            116
#define OP_STRUCTUREDBUFFER            117
#define OP_POINTSTREAM                 118
#define OP_LINESTREAM                  119
#define OP_TRIANGLESTREAM              120
#define OP_STRUCT                      121
#define OP_SAMPLER_STATE               122
#define OP_IF                          123
#define OP_ELSE                        124
#define OP_WHILE                       125
#define OP_DO                          126
#define OP_FOR                         127
#define OP_SWITCH                      128
#define OP_CASE                        129
#define OP_DEFAULT                     130
#define OP_CONTINUE                    131
#define OP_BREAK                       132
#define OP_RETURN                      133
#define OP_DISCARD                     134
#define OP_TECHNIQUE                   135
#define OP_PASS                        136
#define OP_COMPILE                     137
#define OP_CBUFFER                     138
#define OP_TBUFFER                     139
