#define PP_INT_CONST                    1
#define PP_CHAR_CONST                   2
#define PP_ID                           3
#define PP_LEFT_PAREN                   4
#define PP_RIGHT_PAREN                  5
#define PP_PLUS                         6
#define PP_DASH                         7
#define PP_BANG                         8
#define PP_TILDE                        9
#define PP_STAR                        10
#define PP_SLASH                       11
#define PP_PERCENT                     12
#define PP_LEFT_OP                     13
#define PP_RIGHT_OP                    14
#define PP_LESS                        15
#define PP_MORE                        16
#define PP_LE_OP                       17
#define PP_GE_OP                       18
#define PP_EQ_OP                       19
#define PP_NE_OP                       20
#define PP_AMPERSAND                   21
#define PP_CARET                       22
#define PP_VERTICAL_BAR                23
#define PP_AND_OP                      24
#define PP_OR_OP                       25
#define PP_QUESTION                    26
#define PP_COLON                       27
